export const USER_ROLES = {
  ORGANIZER: 'ORGANIZER',
  COLLECTOR: 'COLLECTOR',
  EMPLOYEE: 'EMPLOYEE'
};

export const TASK_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  OVERDUE: 'OVERDUE'
};

export const MEETING_STATUS = {
  SCHEDULED: 'SCHEDULED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED'
};

export const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8080/api';